from . import views_cards
from . import views_crud_aeronaves
from . import views_crud_baterias
from . import views_crud_checklists
from . import views_crud_efetivo
from . import views_crud_missao
from . import views_crud_relatorio
from . import views_dashboard_cards
from . import views_funcoes_auxiliares
from . import views_main
from . import views_send_email