from .views_crud_aeronaves import *
from .views_crud_baterias import *
from .views_crud_checklists import *
from .views_crud_missao import *
from .views_crud_relatorio import *
from .views_funcoes_auxiliares import *
from .views_main import *
from .views_points_of_interest import *
from .views_incidentes import *
from .views_legislation import *
from .views_risk_assessment import *