from .views_cards import *
from .views_crud_aeronaves import *
from .views_crud_baterias import *
from .views_crud_checklists import *
from .views_crud_efetivo import *
from .views_crud_missao import *
from .views_crud_relatorio import *
from .views_dashboard_cards import *
from .views_funcoes_auxiliares import *
from .views_main import *
from .views_send_email import *
from .views_points_of_interest import *