cards = [
    {   'title': 'Missões',
        'badge': 'bg-success',
        'url_do_icone': "/static/controle/img/drone.svg",
        'url_da_tabela': "/rpa_manager/principal",
        'novo_elemento': '/rpa_manager/criar_nova_missao',
        'title_novo_elemento': 'Missão'},
    {   'title': 'Checklists',
        'badge': 'bg-info',
        'url_do_icone': "/static/controle/img/checklist.svg",
        'url_da_tabela': "/rpa_manager/checklists",
        'novo_elemento': '/rpa_manager/checklist_form',
        'title_novo_elemento': 'Checklist'},
    {   'title': 'Efetivo',
        'badge': 'bg-success',
        'url_do_icone': "/static/controle/img/person.svg",
        'url_da_tabela': "/rpa_manager/efetivo",
        'novo_elemento': '/rpa_manager/criar_novo_militar',
        'title_novo_elemento': 'Efetivo'},
    {   'title': 'Aeronaves',
        'badge': 'bg-warning',
        'url_do_icone': "/static/controle/img/aircrafts.svg",
        'url_da_tabela': "/rpa_manager/aeronaves",
        'novo_elemento': '/rpa_manager/criar_nova_aeronave',
        'title_novo_elemento': 'Aeronave'},
    {   'title': 'Baterias',
        'badge': 'bg-danger',
        'url_do_icone': "/static/controle/img/battery.svg",
        'url_da_tabela': "/rpa_manager/baterias",
        'novo_elemento': '/rpa_manager/criar_nova_bateria',
        'title_novo_elemento': 'Bateria'},
    {   'title': 'Relatórios',
        'badge': 'bg-warning',
        'url_do_icone': "/static/controle/img/report.svg",
        'url_da_tabela': "/rpa_manager/relatorios"},
    {   'title': 'Estatísticas',
        'badge': 'bg-success',
        'url_do_icone': "/static/controle/img/statistics.svg",
        'url_da_tabela': '/rpa_manager/dashboard'},
]
