version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$STAGE_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$STAGE_DJANGO_SITE_ID
      - ALLOWED_HOSTS=172.16.150.140,.stage.pm.pb.gov.br
      - DB_NAME=$STAGE_DB_NAME
      - DB_USER=$STAGE_DB_USER
      - DB_PASSWORD=$STAGE_DB_PASSWORD
      - DB_HOST=$STAGE_DB_HOST
      - DB_PORT=$STAGE_DB_PORT
      - MINIO_ENDPOINT=$STAGE_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$STAGE_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$STAGE_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$STAGE_MINIO_SECRET_KEY
      - SERVICES_HOST=$STAGE_SERVICES_HOST
      - SERVICES_SECRET=$STAGE_SERVICES_SECRET
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$STAGE_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$STAGE_KEYCLOAK_REALM
      - KEYCLOAK_URL=$STAGE_KEYCLOAK_URL
      - SOCIAL_AUTH_KEYCLOAK_KEY=$STAGE_SOCIAL_AUTH_KEYCLOAK_KEY
      - SOCIAL_AUTH_KEYCLOAK_SECRET=$STAGE_SOCIAL_AUTH_KEYCLOAK_SECRET
      - SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY=$STAGE_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY
      - SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL=$STAGE_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL
      - SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL=$STAGE_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL
      - CELERY_BROKER_URL=$STAGE_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$STAGE_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$STAGE_GRAYLOG_HTTP_ENDPOINT
      - PORTAL_TOKEN=$STAGE_PORTAL_TOKEN
      - PORTAL_URL_BASE=$STAGE_PORTAL_URL_BASE

    command: bash -c -o pipefail "python manage.py migrate 
      && python manage.py collectstatic --noinput
      && python manage.py test"

