version: "3.8"

services:
  # Django app
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      - DEBUG=on
      - SECRET_KEY=minha_senha_secreta_aqui
      - DB_NAME=django
      - DB_USER=django
      - DB_PASSWORD=django
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Postgres Database
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

volumes:
  postgres_data:
