version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$PROD_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$PROD_DJANGO_SITE_ID
      - ALLOWED_HOSTS=10.0.1.40,.apps.pm.pb.gov.br
      - DB_NAME=$PROD_DB_NAME
      - DB_USER=$PROD_DB_USER
      - DB_PASSWORD=$PROD_DB_PASSWORD
      - DB_HOST=$PROD_DB_HOST
      - DB_PORT=$PROD_DB_PORT
      - MINIO_ENDPOINT=$PROD_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$PROD_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$PROD_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$PROD_MINIO_SECRET_KEY
      - WATERMARK_ACTIVE=$PROD_WATERMARK_ACTIVE
      - WATERMARK_HOST=$PROD_WATERMARK_HOST
      - WATERMARK_SECRET=$PROD_WATERMARK_SECRET
      - SERVICES_URL=$PROD_SERVICES_URL
      - SERVICES_ENDPOINT_MARK=$PROD_SERVICES_ENDPOINT_MARK
      - SERVICES_TOKEN=$PROD_SERVICES_TOKEN
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$PROD_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM
      - KEYCLOAK_URL=$PROD_KEYCLOAK_URL
      - SOCIAL_AUTH_KEYCLOAK_KEY=$PROD_SOCIAL_AUTH_KEYCLOAK_KEY
      - SOCIAL_AUTH_KEYCLOAK_SECRET=$PROD_SOCIAL_AUTH_KEYCLOAK_SECRET
      - SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY=$PROD_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY
      - SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL=$PROD_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL
      - SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL=$PROD_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$PROD_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$PROD_GRAYLOG_HTTP_ENDPOINT
      - PORTAL_TOKEN=$PROD_PORTAL_TOKEN
      - PORTAL_URL_BASE=$PROD_PORTAL_URL_BASE

    command: bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn --bind 0.0.0.0:8000 --workers 9 project.wsgi:application"
    volumes:
      - ./logs:/code/logs
    ports:
      - "8000:8000"
    restart: always

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$PROD_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$PROD_DJANGO_SITE_ID
      - ALLOWED_HOSTS=10.0.1.56,.apps.pm.pb.gov.br    
      - DB_NAME=$PROD_DB_NAME
      - DB_USER=$PROD_DB_USER
      - DB_PASSWORD=$PROD_DB_PASSWORD
      - DB_HOST=$PROD_DB_HOST
      - DB_PORT=$PROD_DB_PORT
      - MINIO_ENDPOINT=$PROD_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$PROD_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$PROD_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$PROD_MINIO_SECRET_KEY
      - WATERMARK_ACTIVE=$PROD_WATERMARK_ACTIVE
      - WATERMARK_HOST=$PROD_WATERMARK_HOST
      - WATERMARK_SECRET=$PROD_WATERMARK_SECRET
      - SERVICES_URL=$PROD_SERVICES_URL
      - SERVICES_ENDPOINT_MARK=$PROD_SERVICES_ENDPOINT_MARK
      - SERVICES_TOKEN=$PROD_SERVICES_TOKEN
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$PROD_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM
      - KEYCLOAK_URL=$PROD_KEYCLOAK_URL
      - SOCIAL_AUTH_KEYCLOAK_KEY=$PROD_SOCIAL_AUTH_KEYCLOAK_KEY
      - SOCIAL_AUTH_KEYCLOAK_SECRET=$PROD_SOCIAL_AUTH_KEYCLOAK_SECRET
      - SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY=$PROD_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY
      - SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL=$PROD_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL
      - SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL=$PROD_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$PROD_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$PROD_GRAYLOG_HTTP_ENDPOINT
      - PORTAL_TOKEN=$PROD_PORTAL_TOKEN
      - PORTAL_URL_BASE=$PROD_PORTAL_URL_BASE

    command: bash -c "celery -A project worker -l info"
    volumes:
      - ./logs:/code/logs
    restart: always
    depends_on:
      - app

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$PROD_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$PROD_DJANGO_SITE_ID
      - ALLOWED_HOSTS=10.0.1.56,.apps.pm.pb.gov.br    
      - DB_NAME=$PROD_DB_NAME
      - DB_USER=$PROD_DB_USER
      - DB_PASSWORD=$PROD_DB_PASSWORD
      - DB_HOST=$PROD_DB_HOST
      - DB_PORT=$PROD_DB_PORT
      - MINIO_ENDPOINT=$PROD_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$PROD_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$PROD_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$PROD_MINIO_SECRET_KEY
      - WATERMARK_ACTIVE=$PROD_WATERMARK_ACTIVE
      - WATERMARK_HOST=$PROD_WATERMARK_HOST
      - WATERMARK_SECRET=$PROD_WATERMARK_SECRET
      - SERVICES_URL=$PROD_SERVICES_URL
      - SERVICES_ENDPOINT_MARK=$PROD_SERVICES_ENDPOINT_MARK
      - SERVICES_TOKEN=$PROD_SERVICES_TOKEN
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$PROD_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM
      - KEYCLOAK_URL=$PROD_KEYCLOAK_URL
      - SOCIAL_AUTH_KEYCLOAK_KEY=$PROD_SOCIAL_AUTH_KEYCLOAK_KEY
      - SOCIAL_AUTH_KEYCLOAK_SECRET=$PROD_SOCIAL_AUTH_KEYCLOAK_SECRET
      - SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY=$PROD_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY
      - SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL=$PROD_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL
      - SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL=$PROD_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$PROD_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$PROD_GRAYLOG_HTTP_ENDPOINT
      - PORTAL_TOKEN=$PROD_PORTAL_TOKEN
      - PORTAL_URL_BASE=$PROD_PORTAL_URL_BASE

    command: bash -c "celery -A project beat -l info"
    volumes:
      - ./logs:/code/logs
    restart: always
    depends_on:
      - app
