version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$PROD_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$PROD_DJANGO_SITE_ID
      - ALLOWED_HOSTS=.apps.pm.pb.gov.br,10.0.1.56 # TODO: atualizar o IP
      - DB_NAME=$PROD_DB_NAME
      - DB_USER=$PROD_DB_USER
      - DB_PASSWORD=$PROD_DB_PASSWORD
      - DB_HOST=$PROD_DB_HOST
      - DB_PORT=$PROD_DB_PORT
      - MINIO_ENDPOINT=$PROD_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$PROD_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$PROD_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$PROD_MINIO_SECRET_KEY
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$PROD_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM
      - KEYCLOAK_URL=$PROD_KEYCLOAK_URL
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$PROD_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$PROD_GRAYLOG_HTTP_ENDPOINT
    command: bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn --bind 0.0.0.0:8000 --workers 9 project.wsgi:application"
    volumes:
      - ./logs:/code/logs
    ports:
      - "8000:8000"
    restart: always

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$PROD_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$PROD_DJANGO_SITE_ID
      - ALLOWED_HOSTS=.apps.pm.pb.gov.br, 10.0.1.56 # TODO: atualizar o IP
      - DB_NAME=$PROD_DB_NAME
      - DB_USER=$PROD_DB_USER
      - DB_PASSWORD=$PROD_DB_PASSWORD
      - DB_HOST=$PROD_DB_HOST
      - DB_PORT=$PROD_DB_PORT
      - MINIO_ENDPOINT=$PROD_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$PROD_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$PROD_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$PROD_MINIO_SECRET_KEY
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$PROD_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM
      - KEYCLOAK_URL=$PROD_KEYCLOAK_URL
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$PROD_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$PROD_GRAYLOG_HTTP_ENDPOINT
    command: bash -c "celery -A project worker -l info"
    volumes:
      - ./logs:/code/logs
    depends_on:
      - app

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: $IMAGE_TAG
    environment:
      - DJANGO_SECRET_KEY=$PROD_DJANGO_SECRET_KEY
      - DJANGO_SITE_ID=$PROD_DJANGO_SITE_ID
      - ALLOWED_HOSTS=.apps.pm.pb.gov.br, 10.0.1.56 # TODO: atualizar o IP
      - DB_NAME=$PROD_DB_NAME
      - DB_USER=$PROD_DB_USER
      - DB_PASSWORD=$PROD_DB_PASSWORD
      - DB_HOST=$PROD_DB_HOST
      - DB_PORT=$PROD_DB_PORT
      - MINIO_ENDPOINT=$PROD_MINIO_ENDPOINT
      - MINIO_EXTERNAL_ENDPOINT=$PROD_MINIO_EXTERNAL_ENDPOINT
      - MINIO_ACCESS_KEY=$PROD_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$PROD_MINIO_SECRET_KEY
      - KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL=$PROD_KEYCLOAK_ACCOUNT_LOGOUT_REDIRECT_URL
      - KEYCLOAK_REALM=$PROD_KEYCLOAK_REALM
      - KEYCLOAK_URL=$PROD_KEYCLOAK_URL
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$PROD_CELERY_RESULT_BACKEND
      - GRAYLOG_HTTP_ENDPOINT=$PROD_GRAYLOG_HTTP_ENDPOINT
    command: bash -c "celery -A project beat -l info"
    volumes:
      - ./logs:/code/logs
    depends_on:
      - app
