version: "3.4"

services:
  app:
    build: .
    env_file:
      - project/.env.container
    command: bash -c "python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    networks:
      - default
    ports:
      - "8000:8000"

  celery:
    build: .
    env_file:
      - project/.env.container
    command: celery -A project worker -l info
    volumes:
      - .:/code
    depends_on:
      - app

  celery-beat:
    build: .
    env_file:
      - project/.env.container
    command: celery -A project beat -l info
    volumes:
      - .:/code
    depends_on:
      - app

networks:
  default:
    name: nginx-proxy
    external: true