# Generated by Django 3.2.8 on 2023-11-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_rename_father_entity_code'),
        ('rpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='entity_support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.entity'),
        ),
        migrations.DeleteModel(
            name='Entities',
        ),
    ]
