# Generated by Django 3.2.8 on 2024-01-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0002_auto_20231129_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='policegroup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
