# Generated by Django 3.2.8 on 2024-05-06 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georeference', '0002_auto_20240123_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('CCD_key', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('occurrence_date', models.DateField()),
                ('dri_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='datahub.driregion')),
                ('ni_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='georeference.area')),
            ],
        ),
        migrations.CreateModel(
            name='NiIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OstensiveArresting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupportingNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovered_car', models.IntegerField(default=0)),
                ('recovered_moto', models.IntegerField(default=0)),
                ('recovered_pickup', models.IntegerField(default=0)),
                ('recovered_truck', models.IntegerField(default=0)),
                ('recovered_other', models.IntegerField(default=0)),
                ('administratively_seized_car', models.IntegerField(default=0)),
                ('administratively_seized_moto', models.IntegerField(default=0)),
                ('administratively_seized_pickup', models.IntegerField(default=0)),
                ('administratively_seized_truck', models.IntegerField(default=0)),
                ('administratively_seized_other', models.IntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='datahub.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money', to='datahub.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locals', to='datahub.incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='ni_indication',
            field=models.ManyToManyField(related_name='incidents', to='datahub.NiIndication'),
        ),
        migrations.AddField(
            model_name='incident',
            name='occurrence_nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='datahub.occurrencenature'),
        ),
        migrations.AddField(
            model_name='incident',
            name='ostensive_arresting',
            field=models.ManyToManyField(related_name='incidents', to='datahub.OstensiveArresting'),
        ),
        migrations.AddField(
            model_name='incident',
            name='supporting_ni',
            field=models.ManyToManyField(related_name='incidents', to='datahub.SupportingNI'),
        ),
        migrations.CreateModel(
            name='Guns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guns_revolver', models.IntegerField(default=0)),
                ('guns_pistol', models.IntegerField(default=0)),
                ('guns_bpistol', models.IntegerField(default=0)),
                ('guns_shotgun', models.IntegerField(default=0)),
                ('guns_carbine', models.IntegerField(default=0)),
                ('guns_mg', models.IntegerField(default=0)),
                ('guns_rifle', models.IntegerField(default=0)),
                ('guns_explosive', models.IntegerField(default=0)),
                ('guns_clump', models.IntegerField(default=0)),
                ('guns_handcrafted', models.IntegerField(default=0)),
                ('guns_simulacrum', models.IntegerField(default=0)),
                ('guns_ammunition', models.IntegerField(default=0)),
                ('guns_bodyarmor', models.IntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guns', to='datahub.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artane', models.IntegerField(default=0)),
                ('lsd', models.IntegerField(default=0)),
                ('ecstasy', models.IntegerField(default=0)),
                ('lolo', models.IntegerField(default=0)),
                ('crack', models.IntegerField(default=0)),
                ('haxixe', models.IntegerField(default=0)),
                ('tch', models.IntegerField(default=0)),
                ('marihuana', models.IntegerField(default=0)),
                ('skank', models.IntegerField(default=0)),
                ('cocaine', models.IntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='datahub.incident')),
            ],
        ),
    ]
