# Generated by Django 3.2.8 on 2024-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0002_auto_20240123_1128'),
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='ni_area',
        ),
        migrations.AddField(
            model_name='incident',
            name='ni_area',
            field=models.ManyToManyField(related_name='incidents', to='georeference.Area'),
        ),
    ]
