# Generated by Django 3.2.8 on 2024-05-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0002_auto_20240123_1128'),
        ('datahub', '0002_auto_20240506_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='ni_area',
        ),
        migrations.AddField(
            model_name='incident',
            name='ni_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='georeference.area'),
        ),
    ]
