# Generated by Django 3.2.8 on 2024-06-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_auto_20240507_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrestings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrestings_minor', models.IntegerField(default=0)),
                ('arrestings_adult', models.IntegerField(default=0)),
                ('arrestings_mp', models.IntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrestings', to='datahub.incident')),
            ],
        ),
    ]
