# Generated by Django 3.2.8 on 2024-06-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_arrestings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccurrenceNature',
            new_name='OccurrenceNaturelist',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='occurrence_nature',
        ),
    ]
