# Generated by Django 3.2.8 on 2024-06-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_auto_20240606_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrencenature', to='datahub.incident')),
                ('occurrence_nature', models.ManyToManyField(related_name='occurrencenature', to='datahub.OccurrenceNaturelist')),
            ],
        ),
    ]
