# Generated by Django 3.2.8 on 2023-01-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecortex',
            name='nomeArrendatario',
        ),
        migrations.RemoveField(
            model_name='vehiclecortex',
            name='nomePossuidor',
        ),
        migrations.RemoveField(
            model_name='vehiclecortex',
            name='nomeProprietario',
        ),
    ]
