# Generated by Django 3.2.8 on 2023-02-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20230125_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registryvehiclecortex',
            old_name='person_renavan_cortex',
            new_name='person_renavam_cortex',
        ),
    ]
