# Generated by Django 3.2.8 on 2023-02-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_person_options'),
        ('vehicle', '0004_vehicle_vehicleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custody_vehicles', to='person.person'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='own_vehicles', to='person.person'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rented_vehicles', to='person.person'),
        ),
    ]
