# Generated by Django 3.2.8 on 2023-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicle_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='signal',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='PLACA'),
        ),
    ]
