# Generated by Django 3.2.8 on 2023-03-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_military_entity'),
        ('vehicle', '0007_alter_vehicle_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicleimages_entity', to='portal.entity'),
        ),
    ]
