# Generated by Django 3.2.8 on 2023-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20230303_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecortex',
            old_name='quaantidadeRestricoesBaseEmplacamento',
            new_name='quantidadeRestricoesBaseEmplacamento',
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='anoUltimoLicenciamnento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='codigoCarroceira',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='codigoSegurancaCRV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='dataEmissaoCRLV',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='dataPreCadastro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='dataReplicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='descricaoOrgaoRegiaoFiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='flagAtivo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='identificadorUnicoVeiculo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='mesAnoValidadeLicenciamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='mesFabricacaoVeiculo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='numeroCRV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='numeroSequenciaCRV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='numeroTipoCRLV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='numeroViaCRV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='placaPreMercosul',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='ufJurisdicaoVeiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='ufFatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
