# Generated by Django 3.2.8 on 2023-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20230404_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecortex',
            name='numeroViaCRLV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='ufDestinoVeiculoFaturado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecortex',
            name='valorIPVA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
