# Generated by Django 3.2.8 on 2023-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20230404_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataAtualizacaoVeiculo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
