# Generated by Django 3.2.8 on 2023-04-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_vehiclecortex_dataatualizacaoveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecortex',
            name='placaPreMercosul',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
