# Generated by Django 3.2.8 on 2023-04-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_vehiclecortex_placapremercosul'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecortex',
            name='indiceNacionalVeiculos',
            field=models.JSONField(null=True),
        ),
    ]
