# Generated by Django 3.2.8 on 2023-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_vehiclecortex_indicenacionalveiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataAtualizacaoAlarme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataAtualizacaoRouboFurto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataAtualizacaoVeiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataDeclaracaoImportacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataEmissaoCRLV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataEmissaoUltimoCRV',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataEmplacamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataHoraAtualizacaoVeiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataLimiteRestricaoTributaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataPreCadastro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecortex',
            name='dataReplicacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
