# Generated by Django 3.2.8 on 2023-12-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20230522_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMovimento', models.BigIntegerField(blank=True, null=True)),
                ('dataPassagem', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=1024, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('vehicle_cortex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moviments_vehicle_cortex', to='vehicle.vehiclecortex')),
            ],
            options={
                'verbose_name': 'movimento',
                'verbose_name_plural': 'movimentos',
            },
        ),
    ]
