# Generated by Django 3.2.8 on 2022-11-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20220901_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição'),
        ),
    ]
