# Generated by Django 3.2.8 on 2023-03-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_military_entity'),
        ('image', '0004_image_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images_entity', to='portal.entity'),
        ),
    ]
