# Generated by Django 3.2.8 on 2023-03-04 00:06

from django.db import migrations

def reverse_set_new_column(apps, schema_editor):
    Image = apps.get_model('image', 'Image')
    for row in Image.objects.all():
        row.entity = None
        row.save()

def set_new_column(apps, schema_editor):
    Military = apps.get_model('portal', 'Military')
    Entity = apps.get_model('portal', 'Entity')
    User = apps.get_model('auth', 'User')
    Image = apps.get_model('image', 'Image')    
    for row in Image.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_image_entity'),
    ]

    operations = [
        migrations.RunPython(set_new_column, reverse_set_new_column)
    ]
