# Generated by Django 3.2.8 on 2023-02-02 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_user_mark', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('mark_128', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-private'), upload_to='user_watermark_128', verbose_name='Marca 128')),
                ('mark_480', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-private'), upload_to='user_watermark_480', verbose_name='Marca 480')),
                ('mark_720', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-private'), upload_to='user_watermark_720', verbose_name='Marca 720')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('temporary_url', models.URLField()),
                ('expiration_date', models.DateTimeField()),
                ('photo', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-private'), upload_to='watermark', verbose_name="Marca d'agua")),
            ],
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Validade')),
                ('mark_text', models.CharField(max_length=6, verbose_name="Marca d'água")),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Marca d'água de usuário",
                'verbose_name_plural': "Marcas d'água de usuários",
                'ordering': ['-created_at'],
            },
        ),
    ]
