# Generated by Django 3.2.8 on 2023-02-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marktemplates',
            name='uuid_user_mark',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
