# Generated by Django 3.2.8 on 2022-11-28 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('numeroCPF', models.CharField(max_length=11, unique=True)),
                ('nomeCompleto', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeMae', models.CharField(blank=True, max_length=255, null=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('situacaoCadastral', models.CharField(blank=True, max_length=50, null=True)),
                ('identificadorResidenteExterior', models.CharField(blank=True, max_length=50, null=True)),
                ('paisResidencia', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('naturezaOcupacao', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacaoPrincipal', models.CharField(blank=True, max_length=50, null=True)),
                ('anoExercicioOcupacao', models.CharField(blank=True, max_length=4, null=True)),
                ('tipoLogradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroLogradouro', models.CharField(blank=True, max_length=10, null=True)),
                ('complementoLogradouro', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('ddd', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('regiaoFiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('anoObito', models.CharField(blank=True, max_length=4, null=True)),
                ('indicadorEstrangeiro', models.CharField(blank=True, max_length=50, null=True)),
                ('dataAtualizacao', models.DateField(blank=True, null=True)),
                ('tituloEleitor', models.CharField(blank=True, max_length=17, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
