# Generated by Django 3.2.8 on 2022-11-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcortex',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personcortex',
            name='complementoLogradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personcortex',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personcortex',
            name='naturezaOcupacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personcortex',
            name='ocupacaoPrincipal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
