# Generated by Django 3.2.8 on 2022-12-19 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0002_auto_20221129_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcortex',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
