# Generated by Django 3.2.8 on 2023-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0003_personcortex_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcortex',
            name='indicadorMoradorEstrangeiro',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personcortex',
            name='latitudeAproximadaLocal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personcortex',
            name='longitudeAproximadaLocal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personcortex',
            name='municipioNaturalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personcortex',
            name='nomeSocial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personcortex',
            name='paisNascimento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personcortex',
            name='ufNaturalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
