# Generated by Django 3.2.8 on 2023-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0004_auto_20230114_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcortex',
            options={'verbose_name': 'Pessoa Cortex', 'verbose_name_plural': 'Pessoas Cortex'},
        ),
        migrations.AlterField(
            model_name='personcortex',
            name='dataAtualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
