# Generated by Django 3.2.8 on 2023-01-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('cortex', '0005_auto_20230114_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryCortex',
            fields=[
                ('registry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.registry')),
                ('person_cortex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='cortex.personcortex')),
            ],
            options={
                'verbose_name': 'Registro Cortex',
                'verbose_name_plural': 'Registros Cortex',
            },
            bases=('base.registry',),
        ),
    ]
