# Generated by Django 3.2.8 on 2023-01-19 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0006_registrycortex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrycortex',
            name='person_cortex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers_cortex', to='cortex.personcortex'),
        ),
    ]
