# Generated by Django 3.2.8 on 2023-01-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0007_alter_registrycortex_person_cortex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrycortex',
            name='person_cortex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='cortex.personcortex'),
        ),
    ]
