# Generated by Django 3.2.8 on 2023-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0008_alter_registrycortex_person_cortex'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcortex',
            name='indiceNacionalPessoas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
