# Generated by Django 3.2.8 on 2023-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0009_personcortex_indicenacionalpessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcortex',
            name='dataAtualizacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personcortex',
            name='dataNascimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
