# Generated by Django 3.2.8 on 2022-12-30 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0006_auto_20221219_1154'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dados', models.JSONField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='person.person')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_alert.alertcortex_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PersonAlertCortex',
            fields=[
                ('alertcortex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alert.alertcortex')),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeMae', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('historico', models.TextField(blank=True, null=True)),
                ('datahora', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('dataNascimento', models.DateField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('anoBo', models.IntegerField(blank=True, null=True)),
                ('numeroOcorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('dataHoraOcorrencia', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('municipioOcorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('ufOcorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('unidadeOcorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('sisId', models.CharField(blank=True, max_length=100, null=True)),
                ('sitId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta Pessoa',
                'verbose_name_plural': 'Alerta Pessoas',
            },
            bases=('alert.alertcortex',),
        ),
        migrations.CreateModel(
            name='VehicleAlertCortex',
            fields=[
                ('alertcortex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alert.alertcortex')),
                ('latitudeOcorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('longitudeOcorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('latitudePassagem', models.CharField(blank=True, max_length=100, null=True)),
                ('longitudePassagem', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.CharField(blank=True, max_length=100, null=True)),
                ('dataPassagem', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('unidadeRegistroBo', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeDeclarante', models.CharField(blank=True, max_length=100, null=True)),
                ('sitOcrId', models.CharField(blank=True, max_length=100, null=True)),
                ('dataOcorrencia', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('municipioPlaca', models.CharField(blank=True, max_length=100, null=True)),
                ('municipioLocal', models.CharField(blank=True, max_length=100, null=True)),
                ('telefoneContato', models.CharField(blank=True, max_length=100, null=True)),
                ('ufPlaca', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroBo', models.CharField(blank=True, max_length=100, null=True)),
                ('ufLocal', models.CharField(blank=True, max_length=100, null=True)),
                ('localPassagem', models.CharField(blank=True, max_length=100, null=True)),
                ('dddContato', models.CharField(blank=True, max_length=100, null=True)),
                ('sisId', models.IntegerField(blank=True, null=True)),
                ('historicoOcorrencia', models.TextField(blank=True, null=True)),
                ('idMovimento', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Alerta Veículo',
                'verbose_name_plural': 'Alerta Veículos',
            },
            bases=('alert.alertcortex',),
        ),
    ]
