# Generated by Django 3.2.8 on 2022-12-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalertcortex',
            old_name='datahora',
            new_name='dataHora',
        ),
    ]
