# Generated by Django 3.2.8 on 2023-01-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalertcortex',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
