# Generated by Django 3.2.8 on 2022-12-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_rename_datahora_personalertcortex_datahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalertcortex',
            name='dataHora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalertcortex',
            name='dataNascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
