# Generated by Django 3.2.8 on 2023-01-04 15:47

from django.db import migrations
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alter_vehiclealertcortex_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalertcortex',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='person_alert_foto', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='vehicle_alert_images', verbose_name='imagem'),
        ),
    ]
