# Generated by Django 3.2.8 on 2022-12-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_auto_20221231_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalertcortex',
            old_name='anoBo',
            new_name='anoBO',
        ),
        migrations.RenameField(
            model_name='personalertcortex',
            old_name='sisId',
            new_name='sisID',
        ),
        migrations.RenameField(
            model_name='personalertcortex',
            old_name='sitId',
            new_name='sitID',
        ),
    ]
