# Generated by Django 3.2.8 on 2023-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20230104_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalertcortex',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalertcortex',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalertcortex',
            name='sisID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='idMovimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='latitudeOcorrencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='latitudePassagem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='longitudeOcorrencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='longitudePassagem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='sitOcrId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
