# Generated by Django 3.2.8 on 2023-01-06 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_auto_20230104_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcortex',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado'),
        ),
    ]
