# Generated by Django 3.2.8 on 2023-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_alerta_cortex_set_default_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalertcortex',
            name='dataHoraOcorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclealertcortex',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
