# Generated by Django 3.2.8 on 2022-10-29 21:36

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da entidade')),
                ('father', models.CharField(default=0, max_length=7, verbose_name='Código da entidade pai')),
                ('child_exists', models.BooleanField(default=False, verbose_name='A entidade tem filhos?')),
                ('category', models.IntegerField(choices=[(0, 'Outras Instituições'), (1, 'Polícia Militar da Paraíba - Ostensivo'), (2, 'Polícia Militar da Paraíba - Inteligência'), (3, 'Acessos Externo - Público Civil')], default=0, verbose_name='Tipo da entidade')),
                ('hierarchy', models.IntegerField(choices=[(0, 'Não definida'), (1, 'Comando Geral'), (2, 'Estado Maior Estratégico'), (3, 'Diretoria'), (4, 'Comando de Policiamento Regional'), (5, 'Batalhão Especializado'), (6, 'Batalhão'), (7, 'Companhia Independente'), (8, 'Companhia'), (9, 'Pelotão'), (10, 'Seção'), (11, 'Setor'), (12, 'Coordenação'), (13, 'Divisão Regional de Inteligência'), (14, 'Núcleo de Inteligência'), (15, 'Inteligência - Núcleos de Inteligência')], default=0, verbose_name='Hierarquia da entidade')),
                ('id_portal', models.IntegerField(default=0, unique=True, verbose_name='Id do Protal')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='Código da entidade')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('rank', models.CharField(max_length=36, verbose_name='Patente')),
                ('name', models.CharField(max_length=256, verbose_name='Nome completo')),
                ('url_image', models.CharField(max_length=256, verbose_name='Endereço da imagem')),
                ('nickname', models.CharField(max_length=100, verbose_name='Nome de guerra')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('register', models.CharField(max_length=7, verbose_name='Matricula')),
                ('activity_status', models.CharField(max_length=100, verbose_name='Regime')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('genre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero')),
                ('email', models.CharField(max_length=256, verbose_name='Email')),
                ('father', models.CharField(max_length=256, verbose_name='Pai')),
                ('mather', models.CharField(max_length=256, verbose_name='Mãe')),
                ('place_of_birth', models.CharField(max_length=64, verbose_name='Naturalidade')),
                ('marital_status', models.CharField(max_length=64, verbose_name='Estado Civil')),
                ('phone', models.CharField(max_length=36, verbose_name='Telefone')),
                ('address', models.CharField(max_length=256, verbose_name='Endereço')),
                ('number', models.CharField(default='S/N', max_length=16, verbose_name='Número')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('zipcode', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('unit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.entity', to_field='id_portal', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Policial Militar',
                'verbose_name_plural': 'Policiais Militares',
                'unique_together': {('register', 'cpf')},
            },
        ),
    ]
