# Generated by Django 3.2.8 on 2022-11-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_military_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='military',
            name='unit',
        ),
    ]
