# Generated by Django 3.2.8 on 2022-11-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_military_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('obs', models.CharField(max_length=255)),
                ('date_start', models.DateField(verbose_name='Data início')),
                ('date_finish', models.DateField(verbose_name='Data fim')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.entity')),
                ('military', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.military')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
            },
        ),
    ]
