# Generated by Django 3.2.8 on 2022-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_historytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='unit',
            field=models.ManyToManyField(through='portal.HistoryTransfer', to='portal.Entity'),
        ),
    ]
