# Generated by Django 3.2.8 on 2022-11-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_military_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransfer',
            name='entity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.entity', to_field='code', verbose_name='Unidade'),
        ),
    ]
