# Generated by Django 3.2.8 on 2022-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_historytransfer_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransfer',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='obs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
