# Generated by Django 3.2.8 on 2022-11-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20221101_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('rank', models.CharField(max_length=36, verbose_name='Patente')),
                ('military', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.military')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
    ]
