# Generated by Django 3.2.8 on 2023-01-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_military_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='military',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Endereço'),
        ),
    ]
