# Generated by Django 3.2.8 on 2023-02-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_military_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='military',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Endereço'),
        ),
    ]
