# Generated by Django 3.2.8 on 2023-02-15 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_military_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransfer',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='obs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
