# Generated by Django 3.2.8 on 2023-03-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20230215_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entity_enjoyer', to='portal.entity'),
            preserve_default=False,
        ),
    ]
