# Generated by Django 3.2.8 on 2023-03-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_military_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='military',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_military', to='portal.entity'),
        ),
    ]
