# Generated by Django 3.2.8 on 2023-07-11 20:11

from django.db import migrations
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_military_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='militaries_pmpb', verbose_name='Image'),
        ),
    ]
