# Generated by Django 3.2.8 on 2023-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_military_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='military',
            name='url_image',
            field=models.CharField(max_length=1024, verbose_name='Endereço da imagem'),
        ),
    ]
