# Generated by Django 3.2.8 on 2023-11-19 18:24

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import localflavor.br.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enjoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nome de usuário')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Último nome')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('phone', models.CharField(blank=True, max_length=36, null=True, verbose_name='Número de telefone')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='enjoyers', verbose_name='Image')),
                ('uuid_portal', models.UUIDField(editable=False, unique=True, verbose_name='UUID no Portal')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('uuid_portal', models.UUIDField(editable=False, unique=True, verbose_name='UUID no Portal')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição da categoria de entidades')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('uuid_portal', models.UUIDField(editable=False, unique=True, verbose_name='UUID no Portal')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do tipo de entidade')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição do tipo')),
            ],
            options={
                'verbose_name': 'Hierarquia Organizacional',
                'verbose_name_plural': 'Hierarquias Organizacionais',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='military',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='code',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='id_portal',
        ),
        migrations.RemoveField(
            model_name='military',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='military',
            name='url_image',
        ),
        migrations.AddField(
            model_name='entity',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='entity',
            name='dad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.entity', verbose_name='Entidade superior'),
        ),
        migrations.AddField(
            model_name='entity',
            name='uuid_portal',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID no Portal'),
        ),
        migrations.AddField(
            model_name='military',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='military',
            name='cnh',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Carteira de Motorista'),
        ),
        migrations.AddField(
            model_name='military',
            name='military_identity',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Identidade Militar'),
        ),
        migrations.AddField(
            model_name='military',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='military',
            name='orgao_expeditor_rg',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Órgão Expeditor'),
        ),
        migrations.AddField(
            model_name='military',
            name='rank',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='military',
            name='rg',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Registro Geral'),
        ),
        migrations.AddField(
            model_name='military',
            name='uuid_portal',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID no Portal'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='father',
            field=models.CharField(default=0, max_length=7, verbose_name='Código da Entidade pai no EM8'),
        ),
        migrations.AlterField(
            model_name='military',
            name='activity_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Regime'),
        ),
        migrations.AlterField(
            model_name='military',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='military',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='military',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='military',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='military',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='military',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='military',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='military', to='portal.entity'),
        ),
        migrations.AlterField(
            model_name='military',
            name='father',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Pai'),
        ),
        migrations.AlterField(
            model_name='military',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='military',
            name='marital_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='military',
            name='mather',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='military',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='military',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de guerra'),
        ),
        migrations.AlterField(
            model_name='military',
            name='number',
            field=models.CharField(blank=True, default='S/N', max_length=16, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='military',
            name='phone',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='military',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='military',
            name='register',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='military',
            name='state',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='military',
            name='zipcode',
            field=localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.DeleteModel(
            name='HistoryTransfer',
        ),
    ]
