# Generated by Django 3.2.8 on 2023-11-19 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0019_auto_20231119_1524'),
        ('protect_network', '0002_auto_20231119_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AddField(
            model_name='enjoyer',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_enjoyer', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='enjoyer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enjoyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='entity', to='portal.Gender', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.organizationalhierarchy', verbose_name='Hierarquia'),
        ),
    ]
