# Generated by Django 3.2.8 on 2023-11-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20231119_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='father',
            new_name='code',
        ),
    ]
