# Generated by Django 3.2.8 on 2024-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_rename_father_entity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enjoyer',
            name='uuid_portal',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID no Portal'),
        ),
    ]
