# Generated by Django 3.2.8 on 2022-09-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
    ]
