# Generated by Django 3.2.8 on 2022-11-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_documentimage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='father',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pai'),
        ),
        migrations.AddField(
            model_name='document',
            name='mother',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mãe'),
        ),
        migrations.AddField(
            model_name='documentimage',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição'),
        ),
    ]
