# Generated by Django 3.2.8 on 2022-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20220815_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='label',
            field=models.CharField(default='nada', max_length=255),
            preserve_default=False,
        ),
    ]
