# Generated by Django 3.2.8 on 2022-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20221103_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
