# Generated by Django 3.2.8 on 2023-03-04 00:06

from django.db import migrations

def reverse_set_new_column(apps, schema_editor):
    Document = apps.get_model('document', 'Document')    
    DocumentImage = apps.get_model('document', 'DocumentImage')
    for row in Document.objects.all():
        row.entity = None
        row.save()    
    for row in DocumentImage.objects.all():
        row.entity = None
        row.save()    
    

def set_new_column(apps, schema_editor):
    Military = apps.get_model('portal', 'Military')
    Entity = apps.get_model('portal', 'Entity')
    User = apps.get_model('auth', 'User')
    Document = apps.get_model('document', 'Document')    
    for row in Document.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()
        
    DocumentImage = apps.get_model('document', 'DocumentImage')    
    for row in DocumentImage.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()


class Migration(migrations.Migration):    

    dependencies = [
        ('document', '0008_auto_20230303_2103'),
    ]

    operations = [
        migrations.RunPython(set_new_column, reverse_set_new_column)
    ]
