# Generated by Django 3.2.8 on 2023-05-24 19:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0005_image_entity'),
        ('portal', '0014_alter_military_entity'),
        ('document', '0008_auto_20230303_2103'),
        ('address', '0003_address_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Característica',
                'verbose_name_plural': 'Tipos Característica',
            },
        ),
        migrations.CreateModel(
            name='InvolvedAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressType', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='document.document')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='image.image')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother', models.CharField(blank=True, max_length=255, null=True)),
                ('father', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('addresses', models.ManyToManyField(through='police_report.InvolvedAddresses', to='address.Address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(through='police_report.InvolvedDocuments', to='document.Document')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='involved_entity', to='portal.entity')),
                ('images', models.ManyToManyField(through='police_report.InvolvedImages', to='image.Image')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ciop_number', models.CharField(blank=True, max_length=255, null=True)),
                ('report_type', models.CharField(blank=True, max_length=255, null=True)),
                ('report_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(verbose_name='Relato')),
                ('qpp', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateField()),
                ('report_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='PoliceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('QPP', models.CharField(blank=True, max_length=255, null=True)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams_comander', to='portal.military')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams_driver', to='portal.military')),
                ('patrolman01', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams_patrolman01', to='portal.military')),
                ('patrolman02', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams_patrolman02', to='portal.military')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams_subunit', to='portal.entity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams_unit', to='portal.entity')),
            ],
            options={
                'verbose_name': 'Guarnição Policial',
                'verbose_name_plural': 'Guarnições Policiais',
            },
        ),
        migrations.CreateModel(
            name='VTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('signal_number', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vtrs_unit', to='portal.entity')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
            },
        ),
        migrations.CreateModel(
            name='ReportWitnesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='police_report.involvedperson')),
            ],
        ),
        migrations.CreateModel(
            name='ReportVictims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='police_report.involvedperson')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSuspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='police_report.involvedperson')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSupportTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
                ('support_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='police_report.policeteam')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRequesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='police_report.involvedperson')),
            ],
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='image.image')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressType', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
                ('police_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.policereport')),
            ],
        ),
        migrations.AddField(
            model_name='policeteam',
            name='vtr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='police_teams', to='police_report.vtr'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='addresses',
            field=models.ManyToManyField(through='police_report.ReportAddresses', to='address.Address'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policereport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policereport',
            name='images',
            field=models.ManyToManyField(through='police_report.ReportImages', to='image.Image'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='operational_subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_subunit_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='operational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_unit_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='police_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='police_report_team', to='police_report.policeteam'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='requesters',
            field=models.ManyToManyField(related_name='report_requesters', through='police_report.ReportRequesters', to='police_report.InvolvedPerson'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='support_teams',
            field=models.ManyToManyField(through='police_report.ReportSupportTeams', to='police_report.PoliceTeam'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='suspects',
            field=models.ManyToManyField(related_name='report_suspects', through='police_report.ReportSuspects', to='police_report.InvolvedPerson'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policereport',
            name='victims',
            field=models.ManyToManyField(related_name='report_victims', through='police_report.ReportVictims', to='police_report.InvolvedPerson'),
        ),
        migrations.AddField(
            model_name='policereport',
            name='witnesses',
            field=models.ManyToManyField(related_name='report_witnesses', through='police_report.ReportWitnesses', to='police_report.InvolvedPerson'),
        ),
        migrations.CreateModel(
            name='PersonalCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('file', stdimage.models.StdImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='personal_characteristic_images', verbose_name='imagem de característica pessoal')),
                ('characteristic_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='personal_characteristics', to='police_report.characteristictype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_characteristic_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_characteristic_entity', to='portal.entity')),
                ('person_involved', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='personal_characteristics', to='police_report.involvedperson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_characteristic_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Característica Pessoal',
                'verbose_name_plural': 'Características Pessoais',
            },
        ),
        migrations.CreateModel(
            name='InvolvedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('measure', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_object_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('police_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_invloved_objects', to='police_report.policereport')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='involved_object_unit', to='portal.entity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_object_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objeto apreendido',
                'verbose_name_plural': 'Objetos apreendidos',
            },
        ),
        migrations.CreateModel(
            name='InvolvedNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='Alcunha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_involved_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nicknames_involved_entity', to='portal.entity')),
                ('involved_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nicknames', to='police_report.involvedperson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_involved_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alcunha',
                'verbose_name_plural': 'Alcunhas',
            },
        ),
        migrations.AddField(
            model_name='involvedimages',
            name='involved_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.involvedperson'),
        ),
        migrations.AddField(
            model_name='involveddocuments',
            name='involved_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.involvedperson'),
        ),
        migrations.AddField(
            model_name='involvedaddresses',
            name='involved_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_report.involvedperson'),
        ),
    ]
