# Generated by Django 3.2.8 on 2023-05-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_military_entity'),
        ('police_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policereport',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='police_reports_entity', to='portal.entity'),
        ),
    ]
