# Generated by Django 3.2.8 on 2022-08-03 14:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=155, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=155, null=True, verbose_name='Cidade')),
                ('state', localflavor.br.models.BRStateField(blank=True, default='PB', max_length=2, null=True, verbose_name='Estado')),
                ('region', models.CharField(blank=True, choices=[('CO', 'Centro-Oeste'), ('N', 'Norte'), ('NE', 'Nordeste'), ('S', 'Sul'), ('SE', 'Sudeste')], default='NE', max_length=2, null=True, verbose_name='Região')),
                ('country', models.CharField(blank=True, default='Brasil', max_length=155, null=True, verbose_name='País')),
                ('zipcode', localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('place', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
