# Generated by Django 3.2.8 on 2022-06-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
