# Generated by Django 3.2.8 on 2022-06-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220623_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='active',
        ),
    ]
