# Generated by Django 3.2.8 on 2023-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pontos de Referência'),
        ),
    ]
