# Generated by Django 3.2.8 on 2023-03-04 00:07

from django.db import migrations    

def set_new_column(apps, schema_editor):
    Military = apps.get_model('portal', 'Military')
    Entity = apps.get_model('portal', 'Entity')
    Address = apps.get_model('address', 'Address')    
    for row in Address.objects.all():
        try:
            user = row.created_by
            entity = Military.objects.get(cpf=user.username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_entity'),
    ]

    operations = [
        migrations.RunPython(set_new_column)
    ]
