# Generated by Django 3.2.8 on 2023-01-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='deleted_by_cascade',
        ),
    ]
