# Generated by Django 3.2.8 on 2023-10-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkresponsible',
            name='rank',
        ),
    ]
