# Generated by Django 3.2.8 on 2023-10-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protect_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='spot',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('imageContact', stdimage.models.StdImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='protect_network_img', verbose_name='Imagem')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protect_network.contactinfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_images_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protect_network.contactimage'),
        ),
    ]
