# Generated by Django 3.2.8 on 2023-10-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
        ('protect_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='cnpj',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='is_headquarters',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protect_network.spot'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da rede')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsible_name', to='portal.military')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='respondible_unit', to='portal.entity')),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protect_network.network'),
        ),
    ]
