# Generated by Django 3.2.8 on 2024-01-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_enjoyer_uuid_portal'),
        ('protect_network', '0002_auto_20231119_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protect_network_spot_username', to='portal.enjoyer'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='user_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protect_network_spot_entity', to='portal.entity'),
        ),
    ]
