# Generated by Django 3.2.8 on 2023-10-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
        ('protect_network', '0002_remove_networkresponsible_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkresponsible',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_responsible', to='portal.promotion'),
        ),
    ]
