# Generated by Django 3.2.8 on 2023-10-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0002_auto_20231016_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='unit',
        ),
    ]
