# Generated by Django 3.2.8 on 2024-01-31 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_enjoyer_uuid_portal'),
        ('georeference', '0002_auto_20240123_1128'),
        ('protect_network', '0002_auto_20231119_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectNetworkSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_score', models.IntegerField(blank=True, null=True)),
                ('next_update', models.IntegerField(blank=True, null=True)),
                ('is_headquarters', models.BooleanField(blank=True, default=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_company', models.CharField(blank=True, max_length=20, null=True)),
                ('QPP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protect_network.qpp')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georeference.spot')),
                ('spot_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protect_network.network')),
                ('tags', models.ManyToManyField(blank=True, to='protect_network.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protect_network_spot_username', to='portal.enjoyer'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protect_network_spot_spottype', to='georeference.spottype'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='user_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protect_network_spot_entity', to='portal.entity'),
        ),
        migrations.DeleteModel(
            name='SpotType',
        ),
    ]
