# Generated by Django 3.2.8 on 2024-02-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0002_auto_20240123_1128'),
        ('protect_network', '0002_auto_20231119_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectNetworkSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_score', models.IntegerField(blank=True, null=True)),
                ('next_update', models.IntegerField(blank=True, null=True)),
                ('is_headquarters', models.BooleanField(blank=True, default=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_company', models.CharField(blank=True, max_length=20, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georeference.spot')),
                ('spot_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protect_network.network')),
                ('tags', models.ManyToManyField(blank=True, to='protect_network.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='QPP',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spot_network',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spot_type',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='user_unit',
        ),
        migrations.RemoveField(
            model_name='spotaddresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='spotaddresses',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='spottype',
            name='spot_type_father',
        ),
        migrations.DeleteModel(
            name='Qpp',
        ),
        migrations.DeleteModel(
            name='SpotAddresses',
        ),
        migrations.DeleteModel(
            name='SpotType',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protect_network.protectnetworkspot'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protect_network.protectnetworkspot'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='protect_network.protectnetworkspot'),
        ),
        migrations.AlterField(
            model_name='securitysurvey',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_survey', to='protect_network.protectnetworkspot'),
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
