# Generated by Django 3.2.8 on 2024-02-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_enjoyer_uuid_portal'),
        ('protect_network', '0003_auto_20240215_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='responsibles',
        ),
        migrations.AlterField(
            model_name='networkresponsible',
            name='responsible',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.military'),
        ),
        migrations.AlterField(
            model_name='protectnetworkspot',
            name='spot_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protect_network.network'),
        ),
        migrations.AlterUniqueTogether(
            name='networkresponsible',
            unique_together=set(),
        ),
    ]
