# Generated by Django 3.2.8 on 2024-01-31 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0003_auto_20240130_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectnetworkspot',
            name='QPP',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protect_network.protectnetworkspot'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protect_network.protectnetworkspot'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='protect_network.protectnetworkspot'),
        ),
        migrations.AlterField(
            model_name='securitysurvey',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_survey', to='protect_network.protectnetworkspot'),
        ),
    ]
