# Generated by Django 3.2.8 on 2024-01-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0002_auto_20240123_1128'),
        ('protect_network', '0003_auto_20240126_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protect_network_spot_spottype', to='georeference.spottype'),
        ),
        migrations.DeleteModel(
            name='SpotType',
        ),
    ]
