# Generated by Django 3.2.8 on 2023-10-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0003_remove_network_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='QPP',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QPP do ponto'),
        ),
    ]
