# Generated by Django 3.2.8 on 2023-10-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
        ('protect_network', '0003_networkresponsible_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkresponsible',
            name='promotion',
        ),
        migrations.AlterField(
            model_name='network',
            name='responsibles',
            field=models.ManyToManyField(through='protect_network.NetworkResponsible', to='portal.Promotion'),
        ),
        migrations.AlterField(
            model_name='networkresponsible',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.promotion'),
        ),
    ]
