# Generated by Django 3.2.8 on 2024-02-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0004_auto_20240131_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectnetworkspot',
            name='qpp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protect_network.qpp'),
        ),
    ]
