# Generated by Django 3.2.8 on 2023-10-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
        ('protect_network', '0004_spot_qpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='responsible',
        ),
        migrations.AddField(
            model_name='network',
            name='responsibles',
            field=models.ManyToManyField(related_name='networks_responsible', to='portal.Military'),
        ),
        migrations.CreateModel(
            name='NetworkResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.military')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protect_network.network')),
            ],
        ),
    ]
