# Generated by Django 3.2.8 on 2024-02-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0005_protectnetworkspot_qpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotaddresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='spotaddresses',
            name='spot',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
        migrations.DeleteModel(
            name='SpotAddresses',
        ),
    ]
