# Generated by Django 3.2.8 on 2023-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0005_auto_20231016_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='parent_company',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
