# Generated by Django 3.2.8 on 2023-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0006_alter_spot_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='details',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='QPP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='is_headquarters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='parent_company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
