# Generated by Django 3.2.8 on 2024-02-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protect_network', '0006_auto_20240202_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectnetworkspot',
            name='qpp',
        ),
    ]
