# Generated by Django 3.2.8 on 2023-09-08 21:43

import apps.rpa_manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_minio_backend.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('prefixo', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('em_uso', models.BooleanField(blank=True, default=False, null=True)),
                ('imagem_aeronave', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('horario', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('num_helices', models.IntegerField(default=4)),
                ('num_baterias', models.IntegerField(default=4)),
                ('baterias_carregadas', models.BooleanField(default=True)),
                ('bateria_controle_carregada', models.BooleanField(default=True)),
                ('corpo', models.BooleanField(default=True)),
                ('hastes_motor', models.BooleanField(default=True)),
                ('helices', models.BooleanField(default=True)),
                ('gimbal', models.BooleanField(default=True)),
                ('holofote', models.BooleanField(default=True)),
                ('auto_falante', models.BooleanField(default=True)),
                ('luz_estroboscopica', models.BooleanField(default=True)),
                ('cabos', models.BooleanField(default=True)),
                ('carregador', models.BooleanField(default=True)),
                ('fonte', models.BooleanField(default=True)),
                ('smart_controller', models.BooleanField(default=True)),
                ('controle', models.BooleanField(default=True)),
                ('cartao_sd', models.BooleanField(default=True)),
                ('IMU', models.BooleanField(default=True)),
                ('compass', models.BooleanField(default=True)),
                ('sinal_transmissao', models.BooleanField(default=True)),
                ('sistema_rtk_ppk', models.BooleanField(default=True)),
                ('sinal_de_video', models.BooleanField(default=True)),
                ('telemetria', models.BooleanField(default=True)),
                ('paraquedas', models.BooleanField(default=True)),
                ('alteracoes', models.TextField(blank=True, null=True)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('piloto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CidadesPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('cidades_pb', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('entidade', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date_published', models.DateField(null=True)),
                ('in_effect', models.BooleanField(default=True)),
                ('legislation_file', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='legislations')),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaDeVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('natureza', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('operacao', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45, unique=True)),
                ('recommended_cicles', models.IntegerField(default=45)),
                ('alert_cicles', models.IntegerField(default=35)),
                ('critical_cicles', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tolerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.probability')),
                ('severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.severity')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=15)),
                ('apllied_legislation', models.TextField(default='')),
                ('keep_distance_from_3rd', models.BooleanField(default=False)),
                ('pilots_capabilities', models.BooleanField(default=True)),
                ('accident_procedure', models.TextField(default='')),
                ('aircrafts', models.ManyToManyField(to='rpa_manager.Aeronave')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('titulo', models.CharField(default='', max_length=250)),
                ('quem_autorizou', models.CharField(blank=True, max_length=100, null=True)),
                ('quem_solicitou', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude')),
                ('arquivo_solicitacao', models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='protocolos')),
                ('num_sarpas', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_ficha_oc', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('relato_da_missao', models.TextField(max_length=500)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('entidade_apoiada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.entidades')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb')),
                ('militar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_militar', to=settings.AUTH_USER_MODEL)),
                ('natureza_de_voo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.naturezadevoo')),
                ('piloto_observador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_piloto_observador', to=settings.AUTH_USER_MODEL)),
                ('tipo_de_operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.tipodeoperacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PontosDeInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude')),
                ('is_temporary', models.BooleanField(default=False)),
                ('date_initial', models.DateTimeField(blank=True, null=True)),
                ('date_final', models.DateTimeField(blank=True, null=True)),
                ('operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.relatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('titulo', models.CharField(max_length=100)),
                ('quem_autorizou', models.CharField(blank=True, max_length=100, null=True)),
                ('quem_solicitou', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('horario', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False, null=True)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb')),
                ('piloto_observador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_piloto_observador', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relato', models.TextField()),
                ('ponto_de_referencia', models.TextField()),
                ('data', models.DateTimeField()),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb')),
                ('operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.relatorio')),
                ('piloto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagensIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageIncidente', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpa_manager.incidentes')),
            ],
        ),
        migrations.CreateModel(
            name='ImagensChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageChecklist', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpa_manager.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAlteracoesAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_aeronave', models.CharField(max_length=45, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.CharField(default=apps.rpa_manager.models.generate_hex_code, max_length=25, unique=True)),
                ('num_helices', models.IntegerField(default=4)),
                ('num_baterias', models.IntegerField(default=4)),
                ('baterias_carregadas', models.BooleanField(default=True)),
                ('bateria_controle_carregada', models.BooleanField(default=True)),
                ('corpo', models.BooleanField(default=True)),
                ('hastes_motor', models.BooleanField(default=True)),
                ('helices', models.BooleanField(default=True)),
                ('gimbal', models.BooleanField(default=True)),
                ('holofote', models.BooleanField(default=True)),
                ('auto_falante', models.BooleanField(default=True)),
                ('luz_estroboscopica', models.BooleanField(default=True)),
                ('cabos', models.BooleanField(default=True)),
                ('carregador', models.BooleanField(default=True)),
                ('fonte', models.BooleanField(default=True)),
                ('smart_controller', models.BooleanField(default=True)),
                ('controle', models.BooleanField(default=True)),
                ('cartao_sd', models.BooleanField(default=True)),
                ('IMU', models.BooleanField(default=True)),
                ('compass', models.BooleanField(default=True)),
                ('sinal_transmissao', models.BooleanField(default=True)),
                ('sistema_rtk_ppk', models.BooleanField(default=True)),
                ('sinal_de_video', models.BooleanField(default=True)),
                ('telemetria', models.BooleanField(default=True)),
                ('paraquedas', models.BooleanField(default=True)),
                ('alteracoes', models.TextField()),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
            ],
        ),
        migrations.CreateModel(
            name='Guarnicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_motorista', to=settings.AUTH_USER_MODEL)),
                ('piloto_observador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_piloto_observador', to=settings.AUTH_USER_MODEL)),
                ('piloto_remoto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_piloto_remoto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('numeracao', models.CharField(max_length=20, unique=True)),
                ('num_ciclos', models.IntegerField()),
                ('imagem_bateria', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem')),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('ciclos_maximo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.typeofbattery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(default='', max_length=2)),
                ('hierarchy_authorization', models.CharField(blank=True, max_length=100, null=True)),
                ('tolerability', models.CharField(default='', max_length=100)),
                ('probability_of_occurrence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.probability')),
                ('risk_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rpa_manager.riskassessment')),
                ('severity_of_occurrence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.severity')),
                ('situation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.situation')),
            ],
        ),
        migrations.AddField(
            model_name='aeronave',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb'),
        ),
    ]
