# Generated by Django 3.2.8 on 2023-07-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('prefixo', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CidadesPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('cidades_pb', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('nome', models.CharField(max_length=20)),
                ('num_baterias', models.IntegerField()),
                ('controle', models.IntegerField()),
                ('fonte', models.IntegerField()),
                ('hub', models.IntegerField()),
                ('cabo_usb', models.IntegerField()),
                ('cabo_energia', models.IntegerField()),
                ('helices', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('nome_de_guerra', models.CharField(max_length=100)),
                ('total_de_horas_voo', models.IntegerField(default=0)),
                ('matricula', models.CharField(max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturezaDeVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('natureza', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('opm', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('operacao', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('unidades', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('titulo', models.CharField(default='', max_length=250)),
                ('data', models.DateField()),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('arquivo_solicitacao', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('num_sarpas', models.CharField(blank=True, max_length=20, null=True)),
                ('relato_da_missao', models.TextField(max_length=500)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb')),
                ('militar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('natureza_de_voo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.naturezadevoo')),
                ('opm_apoiada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.opm')),
                ('piloto_observador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rpa_manager.militar')),
                ('tipo_de_operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.tipodeoperacao')),
                ('unidade_apoiada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.unidades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('titulo', models.CharField(max_length=100)),
                ('horario', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False, null=True)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb')),
                ('piloto_observador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rpa_manager.militar')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='militar',
            name='roles',
            field=models.ManyToManyField(to='rpa_manager.Roles'),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('horario', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('num_helices', models.IntegerField(default=4)),
                ('num_baterias', models.IntegerField(default=4)),
                ('baterias_carregadas', models.BooleanField(default=True)),
                ('bateria_controle_carregada', models.BooleanField(default=True)),
                ('corpo', models.BooleanField(default=True)),
                ('hastes_motor', models.BooleanField(default=True)),
                ('helices', models.BooleanField(default=True)),
                ('gimbal', models.BooleanField(default=True)),
                ('holofote', models.BooleanField(default=True)),
                ('auto_falante', models.BooleanField(default=True)),
                ('luz_estroboscopica', models.BooleanField(default=True)),
                ('cabos', models.BooleanField(default=True)),
                ('carregador', models.BooleanField(default=True)),
                ('fonte', models.BooleanField(default=True)),
                ('smart_controller', models.BooleanField(default=True)),
                ('controle', models.BooleanField(default=True)),
                ('cartao_sd', models.BooleanField(default=True)),
                ('IMU', models.BooleanField(default=True)),
                ('compass', models.BooleanField(default=True)),
                ('sinal_transmissao', models.BooleanField(default=True)),
                ('sistema_rtk_ppk', models.BooleanField(default=True)),
                ('sinal_de_video', models.BooleanField(default=True)),
                ('telemetria', models.BooleanField(default=True)),
                ('paraquedas', models.BooleanField(default=True)),
                ('alteracoes', models.TextField(blank=True, null=True)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('piloto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('numeracao', models.CharField(max_length=20)),
                ('num_ciclos', models.IntegerField()),
                ('ciclos_maximo', models.IntegerField(default=45)),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave')),
                ('maleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.maleta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aeronave',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb'),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='maleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.maleta'),
        ),
    ]
