# Generated by Django 3.2.8 on 2023-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='operational_scenario',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='accident_procedure',
            field=models.TextField(default='Corpo de Bombeiros Militar da Paraíba, SAMU, Socorristas, Brigadistas. Deverá ser informado o ocorrido ao CIOP, solicitando o apoio necessário, ou procurar pelo responsável.'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='apllied_legislation',
            field=models.TextField(default='Lei nº 7.565/1986 – CBA; RBAC-E 94; ICA 100-40, MCA 56-5; IS nº E94-003'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='operator',
            field=models.CharField(default='POLÍCIA MILITAR DO ESTADO DA PARAÍBA', max_length=100),
        ),
    ]
