# Generated by Django 3.2.8 on 2023-07-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='entidade_apoiada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.entidades'),
        ),
    ]
