# Generated by Django 3.2.8 on 2023-11-18 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
        ('rpa_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policegroup',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_driver', to='portal.military'),
        ),
        migrations.AlterField(
            model_name='policegroup',
            name='observer_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_observer_pilot', to='portal.military'),
        ),
        migrations.AlterField(
            model_name='policegroup',
            name='remote_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_remote_pilot', to='portal.military'),
        ),
    ]
