# Generated by Django 3.2.8 on 2023-10-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicrafthistoric',
            name='carregador',
        ),
    ]
