# Generated by Django 3.2.8 on 2023-09-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0002_auto_20230911_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='cpf',
            new_name='cnpj',
        ),
    ]
