# Generated by Django 3.2.8 on 2023-07-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0002_auto_20230712_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
