# Generated by Django 3.2.8 on 2023-07-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0002_relatorio_entidade_apoiada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarnicao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
