# Generated by Django 3.2.8 on 2023-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0003_relatorio_data_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='em_uso',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
