# Generated by Django 3.2.8 on 2023-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0003_rename_cpf_riskassessment_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='cnpj',
            field=models.CharField(default='08.907.776/0001-00', max_length=18),
        ),
    ]
