# Generated by Django 3.2.8 on 2023-11-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_military_user'),
        ('rpa_manager', '0003_alter_operation_observer_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='observer_pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_observer_pilot', to='portal.military'),
        ),
    ]
