# Generated by Django 3.2.8 on 2023-09-12 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpa_manager', '0004_alter_riskassessment_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='mitigation_measures_risk',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='info_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='responsible_sign',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
