# Generated by Django 3.2.8 on 2023-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0004_auto_20230727_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='missao',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude'),
        ),
    ]
