# Generated by Django 3.2.8 on 2023-07-17 14:39

import apps.rpa_manager.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0004_aeronave_em_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracoesAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteracoes', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.CharField(default=apps.rpa_manager.models.generate_hex_code, max_length=25, unique=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpa_manager.aeronave')),
            ],
        ),
    ]
