# Generated by Django 3.2.8 on 2023-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0005_auto_20230912_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
    ]
