# Generated by Django 3.2.8 on 2023-07-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0005_auto_20230728_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosDeInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude')),
                ('operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.relatorio')),
            ],
        ),
    ]
