# Generated by Django 3.2.8 on 2023-07-17 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0005_historicoalteracoesaeronave'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoalteracoesaeronave',
            name='checklist_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
