# Generated by Django 3.2.8 on 2023-08-01 16:26

from django.db import migrations
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0006_pontosdeinteresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='imagem_aeronave',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
