# Generated by Django 3.2.8 on 2023-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0006_alter_relatorio_horario_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentes',
            name='numero_ficha_oc',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
