# Generated by Django 3.2.8 on 2023-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0007_auto_20230717_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='quem_autorizou',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='quem_solicitou',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
