# Generated by Django 3.2.8 on 2023-08-02 13:36

from django.db import migrations
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0007_aeronave_imagem_aeronave'),
    ]

    operations = [
        migrations.AddField(
            model_name='bateria',
            name='imagem_bateria',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
