# Generated by Django 3.2.8 on 2023-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0008_auto_20230721_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='quem_autorizou',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='quem_solicitou',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
