# Generated by Django 3.2.8 on 2023-08-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0009_auto_20230802_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='maleta',
        ),
    ]
