# Generated by Django 3.2.8 on 2023-07-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0009_auto_20230721_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='latitude',
            field=models.FloatField(default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='longitude',
            field=models.FloatField(default=0.0, null=True, verbose_name='Longitude'),
        ),
    ]
