# Generated by Django 3.2.8 on 2023-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0010_auto_20230724_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude'),
        ),
    ]
