# Generated by Django 3.2.8 on 2023-08-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0010_remove_aeronave_maleta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maleta',
        ),
    ]
