# Generated by Django 3.2.8 on 2023-09-13 13:51

from django.db import migrations
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0010_alter_riskassessment_responsible_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='responsible_sign',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
