# Generated by Django 3.2.8 on 2023-09-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0011_alter_riskassessment_responsible_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entidades',
            new_name='Entities',
        ),
    ]
