# Generated by Django 3.2.8 on 2023-08-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0011_delete_maleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofbattery',
            name='alert_cicles',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='typeofbattery',
            name='critical_cicles',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='typeofbattery',
            name='name',
            field=models.CharField(default='aircraft_model', max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='typeofbattery',
            name='recommended_cicles',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='bateria',
            name='ciclos_maximo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.typeofbattery'),
        ),
    ]
