# Generated by Django 3.2.8 on 2023-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0012_auto_20230919_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='probability',
            name='probability_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='severity',
            name='severity_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='probability',
            name='probability',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='severity',
            name='severity',
            field=models.CharField(default='', max_length=1),
        ),
    ]
