# Generated by Django 3.2.8 on 2023-07-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0012_alter_checklist_aeronave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoalteracoesaeronave',
            name='aeronave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rpa_manager.aeronave'),
        ),
    ]
