# Generated by Django 3.2.8 on 2023-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0012_auto_20230802_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofbattery',
            name='name',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
    ]
