# Generated by Django 3.2.8 on 2023-07-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0013_alter_historicoalteracoesaeronave_aeronave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='aeronave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave'),
        ),
        migrations.AlterField(
            model_name='historicoalteracoesaeronave',
            name='aeronave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave'),
        ),
    ]
