# Generated by Django 3.2.8 on 2023-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0014_historicoalteracoesaeronave_titulo_aeronave'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='numero_ficha_oc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
