# Generated by Django 3.2.8 on 2023-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0014_auto_20230919_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probability',
            name='probability',
            field=models.CharField(choices=[('Nível 1 (muito improvável): é quase impossível que o evento ocorra', '1'), ('Nível 2 (improvável): é bastante improvável que ocorra e não se tem notícia de que tenha alguma vez ocorrido', '2'), ('Nível 3 (remoto): é improvável, mas é possível que venha a ocorrer, ou ocorre raramente', '3'), ('Nível 4 (ocasional): é provável que ocorra algumas vezes, ou historicamente tem ocorrido com pouca frequência', '4'), ('Nível 5 (frequente): é provável que ocorra muitas vezes, ou historicamente tem ocorrido frequentemente', '5')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='severity',
            name='severity',
            field=models.CharField(choices=[('Nível A (catastrófico): morte de múltiplas pessoas', 'A'), ('Nível B (crítico): morte de pessoa, lesões gravíssimas, capazes de deixar sequelas significativas e/ou incapacitantes, tais como cegueira, paralisia, amputações, etc', 'B'), ('Nível C (significativo): lesões sérias a pessoas, mas não incapacitantes nem com sequelas significativas', 'C'), ('Nível D (pequeno): incidentes menores, danos a objetos, animais ou vegetação no solo, lesões leves', 'D'), ('Nível E (insignificante): somente danos ao equipamento', 'E')], default='', max_length=200),
        ),
    ]
