# Generated by Django 3.2.8 on 2023-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0015_relatorio_numero_ficha_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo_solicitacao',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/%Y/%m/%d/'),
        ),
    ]
