# Generated by Django 3.2.8 on 2023-08-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0016_alter_relatorio_arquivo_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='numero_ficha_oc',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
