# Generated by Django 3.2.8 on 2023-08-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0017_alter_relatorio_numero_ficha_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoalteracoesaeronave',
            name='titulo_aeronave',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
