# Generated by Django 3.2.8 on 2023-08-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0018_alter_historicoalteracoesaeronave_titulo_aeronave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentes',
            old_name='localizacao',
            new_name='ponto_de_referencia',
        ),
        migrations.AddField(
            model_name='incidentes',
            name='aeronave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.aeronave'),
        ),
        migrations.AddField(
            model_name='incidentes',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.cidadespb'),
        ),
    ]
