# Generated by Django 3.2.8 on 2023-08-04 20:30

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0019_auto_20230804_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bateria',
            name='imagem',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo_solicitacao',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/'),
        ),
    ]
