# Generated by Django 3.2.8 on 2023-08-04 20:33

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0020_auto_20230804_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bateria',
            name='imagem',
        ),
        migrations.AddField(
            model_name='incidentes',
            name='imagem',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens'),
        ),
    ]
