# Generated by Django 3.2.8 on 2023-08-04 21:23

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0021_auto_20230804_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentes',
            name='imageIncidente',
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo_solicitacao',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='protocolos'),
        ),
        migrations.CreateModel(
            name='ImagensIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageIncidente', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpa_manager.incidentes')),
            ],
        ),
    ]
