# Generated by Django 3.2.8 on 2023-08-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0022_auto_20230804_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentes',
            name='imagem',
        ),
    ]
