# Generated by Django 3.2.8 on 2023-08-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0024_incidentes_piloto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosdeinteresse',
            name='date_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontosdeinteresse',
            name='date_initial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontosdeinteresse',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontosdeinteresse',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
