# Generated by Django 3.2.8 on 2023-08-18 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpa_manager', '0026_remove_pontosdeinteresse_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teste_usuario_rel', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teste_usuario_rel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
