# Generated by Django 3.2.8 on 2023-08-18 19:18

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0027_testeusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageIncidente', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='imagens', verbose_name='Imagem')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpa_manager.checklist')),
            ],
        ),
    ]
