# Generated by Django 3.2.8 on 2023-08-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0028_imagenschecklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenschecklist',
            old_name='imageIncidente',
            new_name='imageChecklist',
        ),
    ]
