# Generated by Django 3.2.8 on 2023-08-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpa_manager', '0032_auto_20230820_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='militar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_militar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='piloto_observador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_piloto_observador', to='rpa_manager.militar'),
        ),
        migrations.DeleteModel(
            name='TesteUsuario',
        ),
    ]
