# Generated by Django 3.2.8 on 2023-08-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0035_auto_20230820_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Militar',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
