# Generated by Django 3.2.8 on 2023-08-28 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpa_manager', '0036_auto_20230820_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarnicao',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gu_motorista', to=settings.AUTH_USER_MODEL),
        ),
    ]
