# Generated by Django 3.2.8 on 2023-09-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0037_alter_guarnicao_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('year_published', models.DateField()),
                ('in_effect', models.BooleanField(default=True)),
            ],
        ),
    ]
