# Generated by Django 3.2.8 on 2023-09-05 23:14

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0038_legislation'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='legislation_file',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='legislations'),
        ),
    ]
