# Generated by Django 3.2.8 on 2023-09-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0039_legislation_legislation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='year_published',
        ),
    ]
