# Generated by Django 3.2.8 on 2023-09-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0040_remove_legislation_year_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
