# Generated by Django 3.2.8 on 2023-09-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0041_legislation_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(default='', max_length=2)),
                ('hierarchy_authorization', models.CharField(blank=True, max_length=100, null=True)),
                ('tolerability', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tolerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.probability')),
                ('severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.severity')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=15)),
                ('apllied_legislation', models.TextField(default='')),
                ('keep_distance_from_3rd', models.BooleanField(default=False)),
                ('pilots_capabilities', models.BooleanField(default=True)),
                ('accident_procedure', models.TextField(default='')),
                ('aircrafts', models.ManyToManyField(to='rpa_manager.Aeronave')),
                ('assessment', models.ManyToManyField(blank=True, related_name='risk_assessments', to='rpa_manager.Assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='probability_of_occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.probability'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='severity_of_occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.severity'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpa_manager.situation'),
        ),
    ]
