# Generated by Django 3.2.8 on 2023-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0042_auto_20230908_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='risk',
            field=models.CharField(default='', max_length=2),
        ),
    ]
