# Generated by Django 3.2.8 on 2023-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_manager', '0043_alter_assessment_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
