# Generated by Django 3.2.8 on 2022-06-22 01:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='PersonNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(max_length=255, verbose_name='Alcunha')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_nicknames', related_query_name='person_nickname', to='person.person')),
            ],
            options={
                'verbose_name': 'Alcunha de Pessoa',
                'verbose_name_plural': 'Alcunhas de Pessoas',
            },
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_documents', related_query_name='person_document', to='person.person')),
            ],
            options={
                'verbose_name': 'Documento de Pessoa',
                'verbose_name_plural': 'Documentos de Pessoas',
            },
        ),
    ]
