# Generated by Django 3.2.8 on 2022-06-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20220623_0141'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apa', related_query_name='apa', to='address.address'),
        ),
    ]
