# Generated by Django 3.2.8 on 2022-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_uuid'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='documents',
            field=models.ManyToManyField(to='document.Document'),
        ),
    ]
