# Generated by Django 3.2.8 on 2022-09-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaddresses',
            old_name='type',
            new_name='addressType',
        ),
    ]
