# Generated by Django 3.2.8 on 2022-08-03 17:17

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='descrição')),
                ('file', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='tatoo_images', verbose_name='Arquivo')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tatoos', to='person.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='descrição')),
                ('value', models.CharField(max_length=255, verbose_name='valor')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicals', to='person.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
