# Generated by Django 3.2.8 on 2022-06-29 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_initial'),
        ('person', '0003_alter_personaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondocument',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_document', related_query_name='person_document', to='person.person'),
        ),
        migrations.AlterField(
            model_name='personnickname',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_nickname', related_query_name='person_nickname', to='person.person'),
        ),
        migrations.CreateModel(
            name='PersonImageFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_person_image_face', related_query_name='image_person_image_face', to='image.image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_image_face', related_query_name='person_image_face', to='person.person')),
            ],
            options={
                'verbose_name': 'Imagem de Face de Pessoa',
                'verbose_name_plural': 'Imagens de Face de Pessoas',
            },
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_person_image', related_query_name='image_person_image', to='image.image')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_image', related_query_name='person_image', to='person.person')),
            ],
            options={
                'verbose_name': 'Imagem de Pessoa',
                'verbose_name_plural': 'Imagens de Pessoas',
            },
        ),
    ]
