# Generated by Django 3.2.8 on 2022-11-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_tattoo_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição'),
        ),
    ]
