# Generated by Django 3.2.8 on 2022-12-16 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_tattoo_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_label', models.CharField(max_length=255, verbose_name='Sistema')),
                ('system_uuid', models.UUIDField()),
                ('status', models.IntegerField(choices=[(0, 'Inexistente'), (1, 'Atualizado'), (2, 'Atualizando'), (3, 'Desatualizado')], default=0, verbose_name='Status do Registro')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='person.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
