# Generated by Django 3.2.8 on 2022-08-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('document', '0003_alter_documentimage_options'),
        ('image', '0001_initial'),
        ('person', '0004_auto_20220804_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='documents',
            field=models.ManyToManyField(blank=True, to='document.Document'),
        ),
        migrations.AlterField(
            model_name='person',
            name='images',
            field=models.ManyToManyField(blank=True, to='image.Image'),
        ),
    ]
