# Generated by Django 3.2.8 on 2022-12-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_registry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.RemoveField(
            model_name='registry',
            name='status',
        ),
    ]
