# Generated by Django 3.2.8 on 2022-08-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20220808_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nickname',
            old_name='nickname',
            new_name='label',
        ),
    ]
