# Generated by Django 3.2.8 on 2023-01-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20221219_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
