# Generated by Django 3.2.8 on 2023-02-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_delete_registry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('person.view_person', 'Can view person'),), 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
