# Generated by Django 3.2.8 on 2023-02-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
