# Generated by Django 3.2.8 on 2023-03-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_military_entity'),
        ('person', '0009_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faces_person_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='nickname',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nicknames_person_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='person',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='physical',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physicals_person_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tattoos_person_entity', to='portal.entity'),
        ),
    ]
