# Generated by Django 3.2.8 on 2023-03-04 00:06
from django.db import migrations

def reverse_set_new_column(apps, schema_editor):
    Face = apps.get_model('person', 'Face')
    Nickname = apps.get_model('person', 'Nickname')
    Physical = apps.get_model('person', 'Physical')
    Tattoo = apps.get_model('person', 'Tattoo')
    Person = apps.get_model('person', 'Person')
    for row in Face.objects.all():
        row.entity = None
        row.save()
    for row in Nickname.objects.all():
        row.entity = None
        row.save()
    for row in Physical.objects.all():
        row.entity = None
        row.save()
    for row in Tattoo.objects.all():
        row.entity = None
        row.save()
    for row in Person.objects.all():
        row.entity = None
        row.save()

def set_new_column(apps, schema_editor):
    Military = apps.get_model('portal', 'Military')
    Entity = apps.get_model('portal', 'Entity')
    User = apps.get_model('auth', 'User')
    Face = apps.get_model('person', 'Face')
    Nickname = apps.get_model('person', 'Nickname')
    Physical = apps.get_model('person', 'Physical')
    Tattoo = apps.get_model('person', 'Tattoo')
    Person = apps.get_model('person', 'Person')    
    for row in Face.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()        
    for row in Nickname.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()        
    for row in Physical.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()        
    for row in Tattoo.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()        
    for row in Person.objects.all():
        try:
            user = row.created_by
            username = User.objects.get(user)
            entity = Military.objects.get(cpf=username).entity
            row.entity = entity
        except:
            row.entity = Entity.objects.get(name='PMPB|QCG|EME|EM 2')
            row.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20230303_2103'),
    ]

    operations = [
        migrations.RunPython(set_new_column, reverse_set_new_column),
    ]
