# Generated by Django 3.2.8 on 2023-03-18 01:57
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20230303_2103'),
    ]

    operations = [
        UnaccentExtension()
    ]