# Generated by Django 3.2.8 on 2023-01-11 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idpessoa', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('alcunha', models.CharField(max_length=255)),
                ('nomeMae', models.CharField(blank=True, max_length=255, null=True)),
                ('nomePai', models.CharField(blank=True, max_length=255, null=True)),
                ('dataNascimento', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=255, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('statusPessoa', models.CharField(blank=True, max_length=255, null=True)),
                ('indiceAssertividade', models.IntegerField(blank=True, null=True)),
                ('tipoBuscaCPF', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnmp_consult_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnmp_consult_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa BNMP',
                'verbose_name_plural': 'Pessoas BNMP',
            },
        ),
    ]
