# Generated by Django 3.2.8 on 2023-03-20 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_suggestion'),
        ('bnmp', '0002_personbnmp_numerocpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbnmp',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='personbnmp',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personbnmp',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='RegistryBNMP',
            fields=[
                ('registry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.registry')),
                ('person_bnmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='bnmp.personbnmp')),
            ],
            options={
                'verbose_name': 'Registro BNMP',
                'verbose_name_plural': 'Registros BNMP',
            },
            bases=('base.registry',),
        ),
        migrations.CreateModel(
            name='MandadoPrisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seqPeca', models.IntegerField(blank=True, null=True)),
                ('dataCriacao', models.DateField(blank=True, null=True)),
                ('numeroProcesso', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroPeca', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoPeca', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeServidor', models.CharField(blank=True, max_length=255, null=True)),
                ('cargoServidor', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeMagistrado', models.CharField(blank=True, max_length=255, null=True)),
                ('textoJustificativaCancelamento', models.CharField(blank=True, max_length=255, null=True)),
                ('dataConfirmacaoServidor', models.DateField(blank=True, null=True)),
                ('dataExpedicao', models.DateField(blank=True, null=True)),
                ('dataConclusao', models.DateField(blank=True, null=True)),
                ('dataExpiracaoPrisaoMandadoPrisao', models.DateField(blank=True, null=True)),
                ('dataVencimentoMandados', models.DateField(blank=True, null=True)),
                ('orgaoJudiciario', models.CharField(blank=True, max_length=255, null=True)),
                ('dataValidade', models.DateField(blank=True, null=True)),
                ('numeroPrazoPrisao', models.CharField(blank=True, max_length=255, null=True)),
                ('dataInfracao', models.DateField(blank=True, null=True)),
                ('descricaoLocalOcorrencia', models.CharField(blank=True, max_length=255, null=True)),
                ('sinteseDecisao', models.TextField(blank=True, max_length=255, null=True)),
                ('tempoPenaAno', models.CharField(blank=True, max_length=255, null=True)),
                ('tempoPenaMes', models.CharField(blank=True, max_length=255, null=True)),
                ('tempoPenaDia', models.CharField(blank=True, max_length=255, null=True)),
                ('descricaoCumprimento', models.TextField(blank=True, max_length=255, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('regimePrisional', models.CharField(blank=True, max_length=255, null=True)),
                ('especiePrisao', models.CharField(blank=True, max_length=255, null=True)),
                ('sigilo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricaoJustificativa', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeEstabelecimentoPrisional', models.CharField(blank=True, max_length=255, null=True)),
                ('dataPrisao', models.DateField(blank=True, null=True)),
                ('ufCustodia', models.CharField(blank=True, max_length=255, null=True)),
                ('municipioCustodia', models.CharField(blank=True, max_length=255, null=True)),
                ('linkMandadoPrisao', models.URLField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnmp_mandado_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandados', to='bnmp.personbnmp')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnmp_mandado_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandado de Prisao',
                'verbose_name_plural': 'Mandados de Prisao',
            },
        ),
    ]
