# Generated by Django 3.2.8 on 2023-03-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmp', '0003_auto_20230319_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandadoprisao',
            name='tipificacaoPenal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
