# Generated by Django 3.2.8 on 2023-03-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmp', '0004_mandadoprisao_tipificacaopenal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandadoprisao',
            name='person',
        ),
        migrations.AddField(
            model_name='mandadoprisao',
            name='person_bnmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandados', to='bnmp.personbnmp'),
        ),
    ]
