# Generated by Django 3.2.8 on 2023-05-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmp', '0005_auto_20230328_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataConclusao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataConfirmacaoServidor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataCriacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataExpedicao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataExpiracaoPrisaoMandadoPrisao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataInfracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataPrisao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataValidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='dataVencimentoMandados',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personbnmp',
            name='dataNascimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
