# Generated by Django 3.2.8 on 2023-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmp', '0006_auto_20230518_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandadoprisao',
            name='descricaoCumprimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandadoprisao',
            name='sinteseDecisao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
