# Generated by Django 3.2.8 on 2023-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmp', '0007_auto_20230519_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandadoprisao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
