# Generated by Django 3.2.8 on 2023-08-09 17:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('accuracy', models.IntegerField()),
                ('emergency', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('id', models.CharField(max_length=20)),
                ('timestampReceived', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'gps',
                'verbose_name_plural': 'gps',
            },
        ),
    ]
