# Generated by Django 3.2.8 on 2023-04-28 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_address_reference'),
        ('person', '0011_auto_20230317_2257'),
        ('portal', '0014_alter_military_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
            ],
            options={
                'verbose_name': 'Fato',
                'verbose_name_plural': 'Fatos',
            },
        ),
        migrations.CreateModel(
            name='FactWitnesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact.fact')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='FactVictims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact.fact')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='FactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Fato',
                'verbose_name_plural': 'Tipos de Fatos',
            },
        ),
        migrations.CreateModel(
            name='FactSuspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact.fact')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='FactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('file', stdimage.models.StdImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='bacinf-media'), upload_to='fact_images', verbose_name='Arquivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_fact_creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_fact_entity', to='portal.entity')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='fact.fact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_fact_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem de Fato',
                'verbose_name_plural': 'Imagens de Fato',
            },
        ),
        migrations.CreateModel(
            name='FactAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fact.fact')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='addresses',
            field=models.ManyToManyField(through='fact.FactAddresses', to='address.Address'),
        ),
        migrations.AddField(
            model_name='fact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fact',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fact',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fact_entity', to='portal.entity'),
        ),
        migrations.AddField(
            model_name='fact',
            name='fact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='fact.facttype'),
        ),
        migrations.AddField(
            model_name='fact',
            name='suspects',
            field=models.ManyToManyField(related_name='suspects', through='fact.FactSuspects', to='person.Person'),
        ),
        migrations.AddField(
            model_name='fact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fact',
            name='victims',
            field=models.ManyToManyField(related_name='victims', through='fact.FactVictims', to='person.Person'),
        ),
        migrations.AddField(
            model_name='fact',
            name='witnesses',
            field=models.ManyToManyField(related_name='witnesses', through='fact.FactWitnesses', to='person.Person'),
        ),
    ]
